name: DAO Box CI

on:
  push:
    branches: ["main", "oktonystark8/dao-34-setup-cicd-pipeline"]
  pull_request:
    branches: ["main", "oktonystark8/dao-34-setup-cicd-pipeline"]

jobs:
  lint:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./packages/daobox-use-aragon
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }} and pnpm
        uses: pnpm/action-setup@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run lint
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./packages/daobox-use-aragon
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }} and pnpm
        uses: pnpm/action-setup@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run build
